language: python

python:
    - "3.5"

services:
    - mongodb
    - redis-server

addons:
    apt:
        sources:
            - elasticsearch-2.x
            - google-chrome
        packages:
            - elasticsearch

cache:
  - pip
  - npm
  - yarn

before_install:
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -y -t stable --allow-unauthenticated elasticsearch
    - sudo apt-get install -y --allow-unauthenticated google-chrome-stable
    - sudo service elasticsearch restart

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - yarn install

script:
    - flake8
    - pytest --disable-pytest-warnings --cov=newsroom
    - npm run lint
    - npm run test
    - npm run build
